<?php

/**
 * @file
 * Contains gallery_migrations.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function gallery_migrations_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the gallery_migrations module.
    case 'help.page.gallery_migrations':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom Migrations for The Gallery Guide') . '</p>';
      return $output;

    default:
  }
}

/**
 * Make sure the URL has the http protocol on.
 *
 * @param string $url
 *   The URL.
 *
 * @return string
 *   The URL with the protocol.
 */
function _gallerymigrations_website_protocol($url) {
  if (!empty($url) && substr($url, 0, 4) != 'http') {
    $url = 'http://' . $url;
  }
  return $url;
}
